name: CI

on:
  pull_request:
    branches: [master]

jobs:
  test:unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test:unit --ci --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
    env:
      CI: true

  test:e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        browser: [webkit, chromium, firefox]
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [10, 12]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: E2E tests
        run: yarn test:e2e --forceExit
        env:
          BROWSER: ${{ matrix.browser }}
    env:
      CI: true
